### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by 13120241790** [TheOne-Xin/presentation-sample#2]
2024-06-03 17:43:58.274 27954-27954 AndroidRuntime          com.example.presentationsample       E  FATAL EXCEPTION: main
                                                                                                    Process: com.example.presentationsample, PID: 27954
                                                                                                    java.lang.IllegalArgumentException: Window type mismatch. Window Context's window type is 2037, while LayoutParams' type is set to 2038. Please create another Window Context via createWindowContext(getDisplay(), 2038, null) to add window with type:2038
                                                                                                    	at android.view.WindowManagerImpl.assertWindowContextTypeMatches(WindowManagerImpl.java:204)
                                                                                                    	at android.view.WindowManagerImpl.applyTokens(WindowManagerImpl.java:182)
                                                                                                    	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:147)
                                                                                                    	at android.app.Dialog.show(Dialog.java:352)
                                                                                                    	at android.app.Presentation.show(Presentation.java:279)
                                                                                                    	at com.example.presentationsample.MainActivity.showPresentation(MainActivity.java:97)
                                                                                                    	at com.example.presentationsample.MainActivity.access$000(MainActivity.java:18)
                                                                                                    	at com.example.presentationsample.MainActivity$1.onClick(MainActivity.java:32)
                                                                                                    	at android.view.View.performClick(View.java:7536)
                                                                                                    	at android.view.View.performClickInternal(View.java:7509)
                                                                                                    	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
                                                                                                    	at android.view.View$PerformClick.run(View.java:29562)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201)
                                                                                                    	at android.os.Looper.loop(Looper.java:288)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8191)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:573)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)

**Comment by TheOne-Xin** [comment]
这个错误是说window类型不匹配，由于Android版本问题导致的。解决方案是找到app/src/main/java/com/example/presentationsample/MyPresentation.java类中的第24行，getWindow().setType(WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY);这一句中TYPE_APPLICATION_OVERLAY改为TYPE_PRESENTATION。
